steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'us-central1-docker.pkg.dev/456822750436/loan-navigator-repo/ui-service:latest', 
      '-f', 'Dockerfile.ui', 
      '.'
    ]
images:
  - 'us-central1-docker.pkg.dev/456822750436/loan-navigator-repo/ui-service:latest'
